-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_FilterTapSystolic_block3.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_FilterTapSystolic_block3
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Tx/RRC Transmit Filter/FIR Interpolator/FIRFilter4/FilterTapSystolic
-- Hierarchy Level: 5
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_FilterTapSystolic_block3 IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din_re                            :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En16
        coeff                             :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En17
        sumIn                             :   IN    std_logic_vector(33 DOWNTO 0);  -- sfix34_En33
        sumOut                            :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En33
        );
END QPSK_src_FilterTapSystolic_block3;


ARCHITECTURE rtl OF QPSK_src_FilterTapSystolic_block3 IS

  -- Signals
  SIGNAL din_re_signed                    : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL coeff_signed                     : signed(16 DOWNTO 0);  -- sfix17_En17
  SIGNAL sumIn_signed                     : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL fTap_din_reg1                    : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17
  SIGNAL fTap_coef_reg1                   : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17
  SIGNAL fTap_din_reg2                    : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17
  SIGNAL fTap_coef_reg2                   : signed(16 DOWNTO 0) := to_signed(16#00000#, 17);  -- sfix17
  SIGNAL fTap_mult_reg                    : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34
  SIGNAL sumOut_tmp                       : signed(33 DOWNTO 0) := to_signed(0, 34);  -- sfix34_En33

BEGIN
  din_re_signed <= signed(din_re);

  coeff_signed <= signed(coeff);

  sumIn_signed <= signed(sumIn);

  -- FilterTapSystolicS
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        sumOut_tmp <= fTap_mult_reg + sumIn_signed;
        fTap_mult_reg <= fTap_din_reg2 * fTap_coef_reg2;
        fTap_din_reg2 <= fTap_din_reg1;
        fTap_coef_reg2 <= fTap_coef_reg1;
        fTap_din_reg1 <= din_re_signed;
        fTap_coef_reg1 <= coeff_signed;
      END IF;
    END IF;
  END PROCESS fTap_process;


  sumOut <= std_logic_vector(sumOut_tmp);

END rtl;

