-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Rx_Input_Mux.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Rx_Input_Mux
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/Rx Input Mux
-- Hierarchy Level: 1
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Rx_Input_Mux IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        TxBus_data_re                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        TxBus_data_im                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        TxBus_valid                       :   IN    std_logic;
        adcBus_data_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        adcBus_data_im                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        adcBus_valid                      :   IN    std_logic;
        rx_src_sel                        :   IN    std_logic;  -- ufix1
        RxBus_data_re                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        RxBus_data_im                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        RxBus_valid                       :   OUT   std_logic
        );
END QPSK_src_Rx_Input_Mux;


ARCHITECTURE rtl OF QPSK_src_Rx_Input_Mux IS

  -- Signals
  SIGNAL TxBus_data_re_signed             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL TxBus_data_im_signed             : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL adcBus_data_re_signed            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL adcBus_data_im_signed            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_re                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_im                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_re_1                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_im_1                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL valid                            : std_logic;
  SIGNAL valid_1                          : std_logic;

BEGIN
  TxBus_data_re_signed <= signed(TxBus_data_re);

  TxBus_data_im_signed <= signed(TxBus_data_im);

  adcBus_data_re_signed <= signed(adcBus_data_re);

  adcBus_data_im_signed <= signed(adcBus_data_im);

  
  data_re <= TxBus_data_re_signed WHEN rx_src_sel = '0' ELSE
      adcBus_data_re_signed;
  
  data_im <= TxBus_data_im_signed WHEN rx_src_sel = '0' ELSE
      adcBus_data_im_signed;

  Delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_re_1 <= to_signed(16#0000#, 16);
        data_im_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        data_re_1 <= data_re;
        data_im_1 <= data_im;
      END IF;
    END IF;
  END PROCESS Delay_1_process;


  RxBus_data_re <= std_logic_vector(data_re_1);

  RxBus_data_im <= std_logic_vector(data_im_1);

  
  valid <= TxBus_valid WHEN rx_src_sel = '0' ELSE
      adcBus_valid;

  Delay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        valid_1 <= '0';
      ELSIF enb = '1' THEN
        valid_1 <= valid;
      END IF;
    END IF;
  END PROCESS Delay_2_process;


  RxBus_valid <= valid_1;

END rtl;

