-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_FilterCoef_block3.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_FilterCoef_block3
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete 
-- FIR Filter/Filter/FilterCoe
-- Hierarchy Level: 7
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_FilterCoef_block3 IS
  PORT( CoefOutP                          :   OUT   vector_of_std_logic_vector17(0 TO 12)  -- sfix17_En19 [13]
        );
END QPSK_src_FilterCoef_block3;


ARCHITECTURE rtl OF QPSK_src_FilterCoef_block3 IS

  -- Signals
  SIGNAL CoefData                         : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_1                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_2                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_3                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_4                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_5                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_6                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_7                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_8                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_9                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_10                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_11                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_12                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefOutP_tmp                     : vector_of_signed17(0 TO 12);  -- sfix17_En19 [13]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(16#00000#, 17);

  -- CoefReg_2
  CoefData_1 <= to_signed(16#00000#, 17);

  -- CoefReg_3
  CoefData_2 <= to_signed(16#00000#, 17);

  -- CoefReg_4
  CoefData_3 <= to_signed(16#00000#, 17);

  -- CoefReg_5
  CoefData_4 <= to_signed(16#00000#, 17);

  -- CoefReg_6
  CoefData_5 <= to_signed(16#00000#, 17);

  -- CoefReg_7
  CoefData_6 <= to_signed(16#00000#, 17);

  -- CoefReg_8
  CoefData_7 <= to_signed(16#00000#, 17);

  -- CoefReg_9
  CoefData_8 <= to_signed(16#00000#, 17);

  -- CoefReg_10
  CoefData_9 <= to_signed(16#00000#, 17);

  -- CoefReg_11
  CoefData_10 <= to_signed(16#00000#, 17);

  -- CoefReg_12
  CoefData_11 <= to_signed(16#00000#, 17);

  -- CoefReg_13
  CoefData_12 <= to_signed(16#00000#, 17);

  CoefOutP_tmp(0) <= CoefData;
  CoefOutP_tmp(1) <= CoefData_1;
  CoefOutP_tmp(2) <= CoefData_2;
  CoefOutP_tmp(3) <= CoefData_3;
  CoefOutP_tmp(4) <= CoefData_4;
  CoefOutP_tmp(5) <= CoefData_5;
  CoefOutP_tmp(6) <= CoefData_6;
  CoefOutP_tmp(7) <= CoefData_7;
  CoefOutP_tmp(8) <= CoefData_8;
  CoefOutP_tmp(9) <= CoefData_9;
  CoefOutP_tmp(10) <= CoefData_10;
  CoefOutP_tmp(11) <= CoefData_11;
  CoefOutP_tmp(12) <= CoefData_12;

  outputgen: FOR k IN 0 TO 12 GENERATE
    CoefOutP(k) <= std_logic_vector(CoefOutP_tmp(k));
  END GENERATE;

END rtl;

