-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Pack_Bits.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Pack_Bits
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Pack Bits
-- Hierarchy Level: 2
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Pack_Bits IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        bitIn                             :   IN    std_logic;
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        validOut                          :   OUT   std_logic
        );
END QPSK_src_Pack_Bits;


ARCHITECTURE rtl OF QPSK_src_Pack_Bits IS

  -- Component Declarations
  COMPONENT QPSK_src_Scalar_to_Vector_Stream_Conversion
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic;
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- boolean [32]
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT QPSK_src_Pack_Vector_block
    PORT( u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- boolean [32]
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_Scalar_to_Vector_Stream_Conversion
    USE ENTITY work.QPSK_src_Scalar_to_Vector_Stream_Conversion(rtl);

  FOR ALL : QPSK_src_Pack_Vector_block
    USE ENTITY work.QPSK_src_Pack_Vector_block(rtl);

  -- Signals
  SIGNAL Scalar_to_Vector_Stream_Conversion_dataOut : std_logic_vector(31 DOWNTO 0);  -- boolean [32]
  SIGNAL Scalar_to_Vector_Stream_Conversion_validOut : std_logic;
  SIGNAL y                                : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Scalar_to_Vector_Stream_Conversion : QPSK_src_Scalar_to_Vector_Stream_Conversion
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => bitIn,
              validIn => validIn,
              dataOut => Scalar_to_Vector_Stream_Conversion_dataOut,  -- boolean [32]
              validOut => Scalar_to_Vector_Stream_Conversion_validOut
              );

  u_Pack_Vector : QPSK_src_Pack_Vector_block
    PORT MAP( u => Scalar_to_Vector_Stream_Conversion_dataOut,  -- boolean [32]
              y => y  -- uint32
              );

  dataOut <= y;

  validOut <= Scalar_to_Vector_Stream_Conversion_validOut;

END rtl;

