-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_MATLAB_Function.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_MATLAB_Function
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Packet Controller/MATLAB Function
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        valid                             :   IN    std_logic;
        syncPulse                         :   IN    std_logic;
        out_rsvd                          :   OUT   std_logic
        );
END QPSK_src_MATLAB_Function;


ARCHITECTURE rtl OF QPSK_src_MATLAB_Function IS

  -- Signals
  SIGNAL Reg                              : std_logic;
  SIGNAL Reg_next                         : std_logic;

BEGIN
  MATLAB_Function_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Reg <= '0';
      ELSIF enb_1_4_0 = '1' THEN
        Reg <= Reg_next;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_process;

  MATLAB_Function_output : PROCESS (Reg, syncPulse, valid)
  BEGIN
    Reg_next <= Reg;
    --MATLAB Function 'QPSK/QPSK Rx/Frequency and Time Synchronizer/Packet Controller/MATLAB Function'
    IF (Reg AND valid) = '1' THEN 
      Reg_next <= '0';
    END IF;
    IF syncPulse = '1' THEN 
      Reg_next <= '1';
    END IF;
    out_rsvd <= Reg;
  END PROCESS MATLAB_Function_output;


END rtl;

