-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Subsystem.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Subsystem
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and 
-- Correction/Phase Ambiguity Estimator/Subsyste
-- Hierarchy Level: 5
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        L                                 :   IN    std_logic;
        H                                 :   IN    std_logic;
        Out2                              :   OUT   std_logic
        );
END QPSK_src_Subsystem;


ARCHITECTURE rtl OF QPSK_src_Subsystem IS

  -- Signals
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Delay6_out1                      : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;

BEGIN
  Logical_Operator1_out1 <=  NOT L;

  Logical_Operator_out1 <= Logical_Operator1_out1 AND Delay6_out1;

  Logical_Operator2_out1 <= H OR Logical_Operator_out1;

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1 <= '1';
      ELSIF enb_1_4_0 = '1' THEN
        Delay6_out1 <= Logical_Operator2_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Out2 <= Delay6_out1;

END rtl;

