-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Pack_Vector_block.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Pack_Vector_block
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Pack Bits/Pack Vector
-- Hierarchy Level: 3
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Pack_Vector_block IS
  PORT( u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- boolean [32]
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END QPSK_src_Pack_Vector_block;


ARCHITECTURE rtl OF QPSK_src_Pack_Vector_block IS

  -- Component Declarations
  COMPONENT QPSK_src_pack_vector
    PORT( u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- boolean [32]
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_pack_vector
    USE ENTITY work.QPSK_src_pack_vector(rtl);

  -- Signals
  SIGNAL y_tmp                            : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_pack_vector : QPSK_src_pack_vector
    PORT MAP( u => u,  -- boolean [32]
              y => y_tmp  -- uint32
              );

  y <= y_tmp;

END rtl;

