-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Pack_Samples.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Pack_Samples
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DMA/Capture Source Mux/Data to uint32/Pack Samples
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Pack_Samples IS
  PORT( u_re                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        u_im                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END QPSK_src_Pack_Samples;


ARCHITECTURE rtl OF QPSK_src_Pack_Samples IS

  -- Component Declarations
  COMPONENT QPSK_src_Pack_Samples_Fcn
    PORT( u_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          u_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_Pack_Samples_Fcn
    USE ENTITY work.QPSK_src_Pack_Samples_Fcn(rtl);

  -- Signals
  SIGNAL y_tmp                            : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Pack_Samples_Fcn : QPSK_src_Pack_Samples_Fcn
    PORT MAP( u_re => u_re,  -- sfix16_En14
              u_im => u_im,  -- sfix16_En14
              y => y_tmp  -- uint32
              );

  y <= y_tmp;

END rtl;

