-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Zero_On_Invalid.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Zero_On_Invalid
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Tx/Output Switch/Zero On Invalid
-- Hierarchy Level: 3
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Zero_On_Invalid IS
  PORT( dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END QPSK_src_Zero_On_Invalid;


ARCHITECTURE rtl OF QPSK_src_Zero_On_Invalid IS

  -- Component Declarations
  COMPONENT QPSK_src_Zeros_Like
    PORT( u_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          u_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y_re                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y_im                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_Zeros_Like
    USE ENTITY work.QPSK_src_Zeros_Like(rtl);

  -- Signals
  SIGNAL y_re                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL y_im                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL y_re_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL y_im_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataIn_re_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataIn_im_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1_re         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiport_Switch_out1_im         : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_Zeros_Like : QPSK_src_Zeros_Like
    PORT MAP( u_re => dataIn_re,  -- sfix16_En14
              u_im => dataIn_im,  -- sfix16_En14
              y_re => y_re,  -- sfix16_En14
              y_im => y_im  -- sfix16_En14
              );

  y_re_signed <= signed(y_re);

  y_im_signed <= signed(y_im);

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  
  Multiport_Switch_out1_re <= y_re_signed WHEN validIn = '0' ELSE
      dataIn_re_signed;
  
  Multiport_Switch_out1_im <= y_im_signed WHEN validIn = '0' ELSE
      dataIn_im_signed;

  dataOut_re <= std_logic_vector(Multiport_Switch_out1_re);

  dataOut_im <= std_logic_vector(Multiport_Switch_out1_im);

END rtl;

