-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Tapped_Delay_Enabled.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Tapped_Delay_Enabled
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Pack Bits/Scalar to Vector Stream Conversion/Tapped Delay Enabled
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_Tapped_Delay_Enabled IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        u                                 :   IN    std_logic;
        en                                :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- boolean [32]
        );
END QPSK_src_Tapped_Delay_Enabled;


ARCHITECTURE rtl OF QPSK_src_Tapped_Delay_Enabled IS

  -- Signals
  SIGNAL Delay_out1                       : std_logic_vector(31 DOWNTO 0);  -- boolean [32]
  SIGNAL Selector_add_temp                : vector_of_signed32(0 TO 30);  -- int32 [31]
  SIGNAL Selector_out1                    : std_logic_vector(30 DOWNTO 0);  -- boolean [31]
  SIGNAL Vector_Concatenate_out1          : std_logic_vector(31 DOWNTO 0);  -- boolean [32]

BEGIN

  Selector_out1_gen: FOR ii_select IN 0 TO 30 GENERATE
    Selector_add_temp(ii_select) <= to_signed(2 + ii_select, 32);
    Selector_out1(ii_select) <= Delay_out1(to_integer(Selector_add_temp(ii_select) - 1));
  END GENERATE Selector_out1_gen;


  Vector_Concatenate_out1_gen: FOR idx0 IN 0 TO 30 GENERATE
    Vector_Concatenate_out1(idx0) <= Selector_out1(idx0);
  END GENERATE;
  Vector_Concatenate_out1(31) <= u;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= (OTHERS => '0');
      ELSIF enb = '1' AND en = '1' THEN
        Delay_out1 <= Vector_Concatenate_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  y <= Delay_out1;

END rtl;

