-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Quadrant_Mapper_block.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Quadrant_Mapper_block
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and 
-- Correction/Phase Ambiguity Corrector/HDL_CMA_core/Quadrant_Mappe
-- Hierarchy Level: 6
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Quadrant_Mapper_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        xin                               :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        yin                               :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        xout                              :   OUT   std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        yout                              :   OUT   std_logic_vector(12 DOWNTO 0)  -- sfix13_En10
        );
END QPSK_src_Quadrant_Mapper_block;


ARCHITECTURE rtl OF QPSK_src_Quadrant_Mapper_block IS

  -- Signals
  SIGNAL xin_signed                       : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL abs_rsvd_y                       : signed(13 DOWNTO 0);  -- sfix14_En10
  SIGNAL abs_rsvd_cast                    : signed(13 DOWNTO 0);  -- sfix14_En10
  SIGNAL xAbs                             : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL xAbsReg                          : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yin_signed                       : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL abs_rsvd_y_1                     : signed(13 DOWNTO 0);  -- sfix14_En10
  SIGNAL abs_rsvd_cast_1                  : signed(13 DOWNTO 0);  -- sfix14_En10
  SIGNAL yAbs                             : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yAbsReg                          : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL XGreaterThanY                    : std_logic;  -- ufix1
  SIGNAL xout_1                           : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yout_1                           : signed(12 DOWNTO 0);  -- sfix13_En10

BEGIN
  xin_signed <= signed(xin);

  abs_rsvd_cast <= resize(xin_signed, 14);
  
  abs_rsvd_y <=  - (abs_rsvd_cast) WHEN xin_signed < to_signed(16#0000#, 13) ELSE
      resize(xin_signed, 14);
  xAbs <= abs_rsvd_y(12 DOWNTO 0);

  DelayxAbs_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        xAbsReg <= to_signed(16#0000#, 13);
      ELSIF enb_1_4_0 = '1' THEN
        xAbsReg <= xAbs;
      END IF;
    END IF;
  END PROCESS DelayxAbs_process;


  yin_signed <= signed(yin);

  abs_rsvd_cast_1 <= resize(yin_signed, 14);
  
  abs_rsvd_y_1 <=  - (abs_rsvd_cast_1) WHEN yin_signed < to_signed(16#0000#, 13) ELSE
      resize(yin_signed, 14);
  yAbs <= abs_rsvd_y_1(12 DOWNTO 0);

  DelayyAbs_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        yAbsReg <= to_signed(16#0000#, 13);
      ELSIF enb_1_4_0 = '1' THEN
        yAbsReg <= yAbs;
      END IF;
    END IF;
  END PROCESS DelayyAbs_process;


  
  XGreaterThanY <= '1' WHEN xAbsReg > yAbsReg ELSE
      '0';

  
  xout_1 <= yAbsReg WHEN XGreaterThanY = '0' ELSE
      xAbsReg;

  xout <= std_logic_vector(xout_1);

  
  yout_1 <= xAbsReg WHEN XGreaterThanY = '0' ELSE
      yAbsReg;

  yout <= std_logic_vector(yout_1);

END rtl;

