-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Magnitude_Squared_block.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Magnitude_Squared_block
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Magnitude 
-- Square
-- Hierarchy Level: 5
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Magnitude_Squared_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        In1_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        Out1                              :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En26
        );
END QPSK_src_Magnitude_Squared_block;


ARCHITECTURE rtl OF QPSK_src_Magnitude_Squared_block IS

  -- Signals
  SIGNAL In1_re_signed                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL In1_im_signed                    : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Delay4_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Delay5_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Product1_out1                    : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Delay9_out1                      : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Delay6_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Delay7_out1                      : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL Product2_out1                    : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Delay8_out1                      : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Add_add_cast                     : signed(32 DOWNTO 0);  -- sfix33_En26
  SIGNAL Add_add_cast_1                   : signed(32 DOWNTO 0);  -- sfix33_En26
  SIGNAL Add_out1                         : signed(32 DOWNTO 0);  -- sfix33_En26
  SIGNAL Delay10_out1                     : signed(32 DOWNTO 0);  -- sfix33_En26

BEGIN
  In1_re_signed <= signed(In1_re);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_4_0 = '1' THEN
        Delay4_out1 <= In1_re_signed;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay5_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_4_0 = '1' THEN
        Delay5_out1 <= In1_re_signed;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Product1_out1 <= Delay4_out1 * Delay5_out1;

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_out1 <= to_signed(0, 32);
      ELSIF enb_1_4_0 = '1' THEN
        Delay9_out1 <= Product1_out1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  In1_im_signed <= signed(In1_im);

  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_4_0 = '1' THEN
        Delay6_out1 <= In1_im_signed;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Delay7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay7_out1 <= to_signed(16#0000#, 16);
      ELSIF enb_1_4_0 = '1' THEN
        Delay7_out1 <= In1_im_signed;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  Product2_out1 <= Delay6_out1 * Delay7_out1;

  Delay8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay8_out1 <= to_signed(0, 32);
      ELSIF enb_1_4_0 = '1' THEN
        Delay8_out1 <= Product2_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  Add_add_cast <= resize(Delay9_out1, 33);
  Add_add_cast_1 <= resize(Delay8_out1, 33);
  Add_out1 <= Add_add_cast + Add_add_cast_1;

  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_out1 <= to_signed(0, 33);
      ELSIF enb_1_4_0 = '1' THEN
        Delay10_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Out1 <= std_logic_vector(Delay10_out1);

END rtl;

