-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_To_Data_Bus_block1.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_To_Data_Bus_block1
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DMA/Capture Source Mux/Data to uint32/To Data Bus
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_To_Data_Bus_block1 IS
  PORT( data                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        valid                             :   IN    std_logic;
        bus_data                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        bus_valid                         :   OUT   std_logic
        );
END QPSK_src_To_Data_Bus_block1;


ARCHITECTURE rtl OF QPSK_src_To_Data_Bus_block1 IS

  -- Signals
  SIGNAL data_unsigned                    : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  bus_data <= data;

  bus_valid <= valid;

END rtl;

