-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_subFilter_block5.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_subFilter_block5
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DAC/Vector Interpolation/FIR Interpolator/FIRFilter1/Filter/subFilter
-- Hierarchy Level: 6
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_subFilter_block5 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 15);  -- sfix16_En14 [16]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(29 DOWNTO 0);  -- sfix30_En28
        doutVld                           :   OUT   std_logic
        );
END QPSK_src_subFilter_block5;


ARCHITECTURE rtl OF QPSK_src_subFilter_block5 IS

  -- Component Declarations
  COMPONENT QPSK_src_FilterTapSystolicWvldInC0_block
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En28
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En28
          );
  END COMPONENT;

  COMPONENT QPSK_src_FilterTapSystolicWvldin_block4
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En28
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En28
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_FilterTapSystolicWvldInC0_block
    USE ENTITY work.QPSK_src_FilterTapSystolicWvldInC0_block(rtl);

  FOR ALL : QPSK_src_FilterTapSystolicWvldin_block4
    USE ENTITY work.QPSK_src_FilterTapSystolicWvldin_block4(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(18 DOWNTO 0);  -- ufix1 [19]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(29 DOWNTO 0);  -- sfix30_En28
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_6                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_7                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_8                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_9                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_9                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_10                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_10                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_11                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_11                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_12                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_12                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_13                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_13                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_14                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_14                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2deadOut                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_15                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL dout_cast                        : signed(29 DOWNTO 0);  -- sfix30_En28
  SIGNAL muxOut                           : signed(29 DOWNTO 0);  -- sfix30_En28
  SIGNAL dout_1_re_tmp                    : signed(29 DOWNTO 0);  -- sfix30_En28

BEGIN
  u_FilterTap_1 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16_En14
              addin => std_logic_vector(addin),  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix16_En14
              tapout => tapout  -- sfix48_En28
              );

  u_FilterTap_2 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix16_En14
              addin => tapout,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix16_En14
              tapout => tapout_1  -- sfix48_En28
              );

  u_FilterTap_3 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix16_En14
              addin => tapout_1,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix16_En14
              tapout => tapout_2  -- sfix48_En28
              );

  u_FilterTap_4 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix16_En14
              addin => tapout_2,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix16_En14
              tapout => tapout_3  -- sfix48_En28
              );

  u_FilterTap_5 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_3,  -- sfix16_En14
              addin => tapout_3,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix16_En14
              tapout => tapout_4  -- sfix48_En28
              );

  u_FilterTap_6 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_4,  -- sfix16_En14
              addin => tapout_4,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix16_En14
              tapout => tapout_5  -- sfix48_En28
              );

  u_FilterTap_7 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_5,  -- sfix16_En14
              addin => tapout_5,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_6,  -- sfix16_En14
              tapout => tapout_6  -- sfix48_En28
              );

  u_FilterTap_8 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_6,  -- sfix16_En14
              addin => tapout_6,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_7,  -- sfix16_En14
              tapout => tapout_7  -- sfix48_En28
              );

  u_FilterTap_9 : QPSK_src_FilterTapSystolicWvldin_block4
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_7,  -- sfix16_En14
              coefIn_0 => coefIn(8),  -- sfix16_En14
              addin => tapout_7,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_8,  -- sfix16_En14
              tapout => tapout_8  -- sfix48_En28
              );

  u_FilterTap_10 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_8,  -- sfix16_En14
              addin => tapout_8,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_9,  -- sfix16_En14
              tapout => tapout_9  -- sfix48_En28
              );

  u_FilterTap_11 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_9,  -- sfix16_En14
              addin => tapout_9,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_10,  -- sfix16_En14
              tapout => tapout_10  -- sfix48_En28
              );

  u_FilterTap_12 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_10,  -- sfix16_En14
              addin => tapout_10,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_11,  -- sfix16_En14
              tapout => tapout_11  -- sfix48_En28
              );

  u_FilterTap_13 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_11,  -- sfix16_En14
              addin => tapout_11,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_12,  -- sfix16_En14
              tapout => tapout_12  -- sfix48_En28
              );

  u_FilterTap_14 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_12,  -- sfix16_En14
              addin => tapout_12,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_13,  -- sfix16_En14
              tapout => tapout_13  -- sfix48_En28
              );

  u_FilterTap_15 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_13,  -- sfix16_En14
              addin => tapout_13,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_14,  -- sfix16_En14
              tapout => tapout_14  -- sfix48_En28
              );

  u_FilterTap_16 : QPSK_src_FilterTapSystolicWvldInC0_block
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_14,  -- sfix16_En14
              addin => tapout_14,  -- sfix48_En28
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2deadOut,  -- sfix16_En14
              tapout => tapout_15  -- sfix48_En28
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(18 DOWNTO 1) <= intdelay_reg(17 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(18);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(16#00000000#, 30);

  addin <= to_signed(0, 48);

  tapout_signed <= signed(tapout_15);

  dout_cast <= tapout_signed(29 DOWNTO 0);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(16#00000000#, 30);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#00000000#, 30);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

