-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_subFilter_block3.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_subFilter_block3
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete 
-- FIR Filter/Filter/subFilte
-- Hierarchy Level: 7
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_subFilter_block3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
        coefIn                            :   IN    vector_of_std_logic_vector17(0 TO 12);  -- sfix17_En19 [13]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(47 DOWNTO 0);  -- sfix48_En33
        doutVld                           :   OUT   std_logic
        );
END QPSK_src_subFilter_block3;


ARCHITECTURE rtl OF QPSK_src_subFilter_block3 IS

  -- Component Declarations
  COMPONENT QPSK_src_FilterTapSystolicWvldin_block3
    PORT( clk                             :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
          coefIn_0                        :   IN    std_logic_vector(16 DOWNTO 0);  -- sfix17_En19
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En33
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(16 DOWNTO 0);  -- sfix17_En14
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En33
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_FilterTapSystolicWvldin_block3
    USE ENTITY work.QPSK_src_FilterTapSystolicWvldin_block3(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(15 DOWNTO 0);  -- ufix1 [16]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(47 DOWNTO 0);  -- sfix48_En33
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En33
  SIGNAL dinDly2                          : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_1                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_3                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_3                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_4                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_4                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_5                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_5                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_6                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_6                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_7                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_7                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_8                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_8                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_9                        : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_9                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_10                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_10                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_11                       : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_11                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2deadOut                   : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL tapout_12                        : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En33
  SIGNAL muxOut                           : signed(47 DOWNTO 0);  -- sfix48_En33
  SIGNAL dout_1_re_tmp                    : signed(47 DOWNTO 0);  -- sfix48_En33

BEGIN
  u_FilterTap_1 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinReg2_0_re,  -- sfix17_En14
              coefIn_0 => coefIn(0),  -- sfix17_En19
              addin => std_logic_vector(addin),  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix17_En14
              tapout => tapout  -- sfix48_En33
              );

  u_FilterTap_2 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2,  -- sfix17_En14
              coefIn_0 => coefIn(1),  -- sfix17_En19
              addin => tapout,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix17_En14
              tapout => tapout_1  -- sfix48_En33
              );

  u_FilterTap_3 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_1,  -- sfix17_En14
              coefIn_0 => coefIn(2),  -- sfix17_En19
              addin => tapout_1,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix17_En14
              tapout => tapout_2  -- sfix48_En33
              );

  u_FilterTap_4 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_2,  -- sfix17_En14
              coefIn_0 => coefIn(3),  -- sfix17_En19
              addin => tapout_2,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix17_En14
              tapout => tapout_3  -- sfix48_En33
              );

  u_FilterTap_5 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_3,  -- sfix17_En14
              coefIn_0 => coefIn(4),  -- sfix17_En19
              addin => tapout_3,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix17_En14
              tapout => tapout_4  -- sfix48_En33
              );

  u_FilterTap_6 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_4,  -- sfix17_En14
              coefIn_0 => coefIn(5),  -- sfix17_En19
              addin => tapout_4,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix17_En14
              tapout => tapout_5  -- sfix48_En33
              );

  u_FilterTap_7 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_5,  -- sfix17_En14
              coefIn_0 => coefIn(6),  -- sfix17_En19
              addin => tapout_5,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_6,  -- sfix17_En14
              tapout => tapout_6  -- sfix48_En33
              );

  u_FilterTap_8 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_6,  -- sfix17_En14
              coefIn_0 => coefIn(7),  -- sfix17_En19
              addin => tapout_6,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_7,  -- sfix17_En14
              tapout => tapout_7  -- sfix48_En33
              );

  u_FilterTap_9 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_7,  -- sfix17_En14
              coefIn_0 => coefIn(8),  -- sfix17_En19
              addin => tapout_7,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_8,  -- sfix17_En14
              tapout => tapout_8  -- sfix48_En33
              );

  u_FilterTap_10 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_8,  -- sfix17_En14
              coefIn_0 => coefIn(9),  -- sfix17_En19
              addin => tapout_8,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_9,  -- sfix17_En14
              tapout => tapout_9  -- sfix48_En33
              );

  u_FilterTap_11 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_9,  -- sfix17_En14
              coefIn_0 => coefIn(10),  -- sfix17_En19
              addin => tapout_9,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_10,  -- sfix17_En14
              tapout => tapout_10  -- sfix48_En33
              );

  u_FilterTap_12 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_10,  -- sfix17_En14
              coefIn_0 => coefIn(11),  -- sfix17_En19
              addin => tapout_10,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_11,  -- sfix17_En14
              tapout => tapout_11  -- sfix48_En33
              );

  u_FilterTap_13 : QPSK_src_FilterTapSystolicWvldin_block3
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              dinReg2_0_re => dinDly2_11,  -- sfix17_En14
              coefIn_0 => coefIn(12),  -- sfix17_En19
              addin => tapout_11,  -- sfix48_En33
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2deadOut,  -- sfix17_En14
              tapout => tapout_12  -- sfix48_En33
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb_1_4_0 = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(15 DOWNTO 1) <= intdelay_reg(14 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(15);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(0, 48);

  addin <= to_signed(0, 48);

  tapout_signed <= signed(tapout_12);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      tapout_signed;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(0, 48);
      ELSIF enb_1_4_0 = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(0, 48);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb_1_4_0 = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

