-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Symbol_FIFO.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Symbol_FIFO
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate Handle/Symbol 
-- FIF
-- Hierarchy Level: 5
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Symbol_FIFO IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        push                              :   IN    std_logic;
        pop                               :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END QPSK_src_Symbol_FIFO;


ARCHITECTURE rtl OF QPSK_src_Symbol_FIFO IS

  -- Component Declarations
  COMPONENT QPSK_src_HDL_FIFO
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Push                            :   IN    std_logic;
          Pop                             :   IN    std_logic;
          Out_re                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out_im                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Empty                           :   OUT   std_logic;
          Full                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_HDL_FIFO
    USE ENTITY work.QPSK_src_HDL_FIFO(rtl);

  -- Signals
  SIGNAL HDL_FIFO_out2                    : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL HDL_FIFO_out3                    : std_logic;
  SIGNAL NOT1_out1                        : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL HDL_FIFO_out1_re                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HDL_FIFO_out1_im                 : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_HDL_FIFO : QPSK_src_HDL_FIFO
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_re => dataIn_re,  -- sfix16_En14
              In_im => dataIn_im,  -- sfix16_En14
              Push => AND1_out1,
              Pop => AND_out1,
              Out_re => HDL_FIFO_out1_re,  -- sfix16_En14
              Out_im => HDL_FIFO_out1_im,  -- sfix16_En14
              Empty => HDL_FIFO_out2,
              Full => HDL_FIFO_out3
              );

  NOT_out1 <=  NOT HDL_FIFO_out2;

  AND_out1 <= pop AND NOT_out1;

  NOT1_out1 <=  NOT HDL_FIFO_out3;

  AND1_out1 <= push AND NOT1_out1;

  dataOut_re <= HDL_FIFO_out1_re;

  dataOut_im <= HDL_FIFO_out1_im;

END rtl;

