-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Compute_Error.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Compute_Error
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Digital AGC/Automatic Gain Control/Compute Error
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Compute_Error IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        error_rsvd                        :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En12
        );
END QPSK_src_Compute_Error;


ARCHITECTURE rtl OF QPSK_src_Compute_Error IS

  -- Component Declarations
  COMPONENT QPSK_src_Magnitude_Squared
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In1_im                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out1                            :   OUT   std_logic_vector(32 DOWNTO 0)  -- sfix33_En28
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_Magnitude_Squared
    USE ENTITY work.QPSK_src_Magnitude_Squared(rtl);

  -- Signals
  SIGNAL Reference_out1                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Magnitude_Squared_Out1           : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL Magnitude_Squared_Out1_signed    : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Subtract_sub_cast                : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL Subtract_sub_cast_1              : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL Subtract_out1                    : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL Delay2_out1                      : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL Data_Type_Conversion_out1        : signed(17 DOWNTO 0);  -- sfix18_En12

BEGIN
  u_Magnitude_Squared : QPSK_src_Magnitude_Squared
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1_re => dataIn_re,  -- sfix16_En14
              In1_im => dataIn_im,  -- sfix16_En14
              Out1 => Magnitude_Squared_Out1  -- sfix33_En28
              );

  Reference_out1 <= to_signed(16#1000#, 16);

  Magnitude_Squared_Out1_signed <= signed(Magnitude_Squared_Out1);

  Subtract_sub_cast <= resize(Reference_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
  Subtract_sub_cast_1 <= resize(Magnitude_Squared_Out1_signed, 34);
  Subtract_out1 <= Subtract_sub_cast - Subtract_sub_cast_1;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= to_signed(0, 34);
      ELSIF enb = '1' THEN
        Delay2_out1 <= Subtract_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Data_Type_Conversion_out1 <= Delay2_out1(33 DOWNTO 16);

  error_rsvd <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

