-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_QPSK_tc.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_QPSK_tc
-- Source Path: QPSK_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_4_0   : 4x slower than clk with last phase
-- enb_1_4_1   : 4x slower than clk with phase 1
-- enb_1_4_2   : 4x slower than clk with phase 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_QPSK_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_4_0                         :   OUT   std_logic;
        enb_1_4_1                         :   OUT   std_logic;
        enb_1_4_2                         :   OUT   std_logic
        );
END QPSK_src_QPSK_tc;


ARCHITECTURE rtl OF QPSK_src_QPSK_tc IS

  -- Signals
  SIGNAL count4                           : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1_4_0_1                      : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_4_1_1                      : std_logic;
  SIGNAL comp_2_tmp                       : std_logic;
  SIGNAL phase_2_tmp                      : std_logic;
  SIGNAL phase_2                          : std_logic;
  SIGNAL enb_1_4_2_1                      : std_logic;

BEGIN
  enb <= clk_enable;

  enb_1_1_1 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 3
  counter_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count4 <= to_unsigned(16#1#, 2);
      ELSIF clk_enable = '1' THEN
        count4 <= count4 + to_unsigned(16#1#, 2);
      END IF;
    END IF;
  END PROCESS counter_4_process;


  
  comp_0_tmp <= '1' WHEN count4 = to_unsigned(16#3#, 2) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_4_0_1 <= phase_0 AND clk_enable;

  enb_1_4_0 <= enb_1_4_0_1;

  
  comp_1_tmp <= '1' WHEN count4 = to_unsigned(16#0#, 2) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_4_1_1 <= phase_1 AND clk_enable;

  enb_1_4_1 <= enb_1_4_1_1;

  
  comp_2_tmp <= '1' WHEN count4 = to_unsigned(16#1#, 2) ELSE
      '0';

  phase_2_tmp <= comp_2_tmp AND clk_enable;

  phase_delay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_2 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_2 <= phase_2_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_2_process;


  enb_1_4_2_1 <= phase_2 AND clk_enable;

  enb_1_4_2 <= enb_1_4_2_1;

END rtl;

