-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Preamble_Bits_Store.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Preamble_Bits_Store
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Tx/Bit Packetizer/Bits Store/Preamble Bits Store
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Preamble_Bits_Store IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rdEn                              :   IN    std_logic;
        rdData                            :   OUT   std_logic;
        rdValid                           :   OUT   std_logic
        );
END QPSK_src_Preamble_Bits_Store;


ARCHITECTURE rtl OF QPSK_src_Preamble_Bits_Store IS

  -- Constants
  CONSTANT Preamble_LUT_table_data        : std_logic_vector(31 DOWNTO 0) := 
    ('0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0',
     '1', '1', '1', '1', '1', '1', '1', '1', '1', '1');  -- ufix1 [32]

  -- Signals
  SIGNAL count_step                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_from                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Addr_Counter_out1                : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count                            : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL count_1                          : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Preamble_LUT_out1                : std_logic;
  SIGNAL RAMDelay_out1                    : std_logic := '0';
  SIGNAL Match_RAMDelay_out1              : std_logic;

BEGIN
  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 25
  count_step <= to_unsigned(16#01#, 5);

  count_from <= to_unsigned(16#00#, 5);

  count <= Addr_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN Addr_Counter_out1 = to_unsigned(16#19#, 5) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_1 <= Addr_Counter_out1 WHEN rdEn = '0' ELSE
      count_value;

  Addr_Counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Addr_Counter_out1 <= to_unsigned(16#00#, 5);
      ELSIF enb = '1' THEN
        Addr_Counter_out1 <= count_1;
      END IF;
    END IF;
  END PROCESS Addr_Counter_process;


  Preamble_LUT_out1 <= Preamble_LUT_table_data(to_integer(Addr_Counter_out1));

  RAMDelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        RAMDelay_out1 <= Preamble_LUT_out1;
      END IF;
    END IF;
  END PROCESS RAMDelay_process;


  Match_RAMDelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Match_RAMDelay_out1 <= '0';
      ELSIF enb = '1' THEN
        Match_RAMDelay_out1 <= rdEn;
      END IF;
    END IF;
  END PROCESS Match_RAMDelay_process;


  rdData <= RAMDelay_out1;

  rdValid <= Match_RAMDelay_out1;

END rtl;

