-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_To_Data_Bus.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_To_Data_Bus
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/From ADC/To Data Bus
-- Hierarchy Level: 2
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_To_Data_Bus IS
  PORT( data_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        data_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        valid                             :   IN    std_logic;
        bus_data_re                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bus_data_im                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bus_valid                         :   OUT   std_logic
        );
END QPSK_src_To_Data_Bus;


ARCHITECTURE rtl OF QPSK_src_To_Data_Bus IS

  -- Signals
  SIGNAL data_re_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_im_signed                   : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  bus_data_re <= data_re;

  bus_data_im <= data_im;

  bus_valid <= valid;

END rtl;

