-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_ThresholdLimiter.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_ThresholdLimiter
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/ThresholdLimiter
-- Hierarchy Level: 5
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_ThresholdLimiter IS
  PORT( x                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
        );
END QPSK_src_ThresholdLimiter;


ARCHITECTURE rtl OF QPSK_src_ThresholdLimiter IS

  -- Signals
  SIGNAL x_signed                         : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL y_tmp                            : signed(31 DOWNTO 0);  -- sfix32_En28

BEGIN
  x_signed <= signed(x);

  --MATLAB Function 'QPSK/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/ThresholdLimiter'
  -- Apply a lower limit to the threshold.
  -- Threshold is computed by summing across 63 samples.
  -- Set lower limit to be equivalent of all 63 samples
  -- having their LSB set to 1 and all others set to 0. 
  
  y_tmp <= to_signed(2684354, 32) WHEN x_signed < to_signed(2684354, 32) ELSE
      x_signed;

  y <= std_logic_vector(y_tmp);

END rtl;

