-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_FIRFilter2_block.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_FIRFilter2_block
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DAC/Vector Interpolation/FIR Interpolator/FIRFilter2
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_FIRFilter2_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En29
        dataOut_im                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En29
        );
END QPSK_src_FIRFilter2_block;


ARCHITECTURE rtl OF QPSK_src_FIRFilter2_block IS

  -- Component Declarations
  COMPONENT QPSK_src_Filter_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En29
          dataOut_im                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En29
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_Filter_block2
    USE ENTITY work.QPSK_src_Filter_block2(rtl);

  -- Signals
  SIGNAL syncReset                        : std_logic;
  SIGNAL dataOut_re_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dataOut_im_tmp                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_FilterBank : QPSK_src_Filter_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => dataIn_re,  -- sfix16_En14
              dataIn_im => dataIn_im,  -- sfix16_En14
              validIn => validIn,
              syncReset => syncReset,
              dataOut_re => dataOut_re_tmp,  -- sfix32_En29
              dataOut_im => dataOut_im_tmp  -- sfix32_En29
              );

  syncReset <= '0';

  dataOut_re <= dataOut_re_tmp;

  dataOut_im <= dataOut_im_tmp;

END rtl;

