-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_To_DAC.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_To_DAC
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DAC
-- Hierarchy Level: 1
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_To_DAC IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        TxBus_data_re                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        TxBus_data_im                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        TxBus_valid                       :   IN    std_logic;
        tx_enable                         :   IN    std_logic;
        tx_output_gain                    :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        dacDataI                          :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- int16 [4]
        dacDataQ                          :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- int16 [4]
        dacValid                          :   OUT   std_logic
        );
END QPSK_src_To_DAC;


ARCHITECTURE rtl OF QPSK_src_To_DAC IS

  -- Component Declarations
  COMPONENT QPSK_src_From_Data_Bus
    PORT( bus_data_re                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          bus_data_im                     :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          bus_valid                       :   IN    std_logic;
          data_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          data_im                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          valid                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT QPSK_src_Apply_Gain_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          tx_output_gain                  :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          dataOut_re                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataOut_im                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT QPSK_src_Vector_Interpolation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          dataOut_im                      :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT QPSK_src_To_DAC_Interface
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          dataIn_im                       :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          validIn                         :   IN    std_logic;
          tx_enable                       :   IN    std_logic;
          dacDataI                        :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- int16 [4]
          dacDataQ                        :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- int16 [4]
          dacValid                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_From_Data_Bus
    USE ENTITY work.QPSK_src_From_Data_Bus(rtl);

  FOR ALL : QPSK_src_Apply_Gain_block
    USE ENTITY work.QPSK_src_Apply_Gain_block(rtl);

  FOR ALL : QPSK_src_Vector_Interpolation
    USE ENTITY work.QPSK_src_Vector_Interpolation(rtl);

  FOR ALL : QPSK_src_To_DAC_Interface
    USE ENTITY work.QPSK_src_To_DAC_Interface(rtl);

  -- Signals
  SIGNAL From_Data_Bus_data_re            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL From_Data_Bus_data_im            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL From_Data_Bus_valid              : std_logic;
  SIGNAL Apply_Gain_dataOut_re            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Apply_Gain_dataOut_im            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Apply_Gain_validOut              : std_logic;
  SIGNAL Vector_Interpolation_dataOut_re  : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]
  SIGNAL Vector_Interpolation_dataOut_im  : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]
  SIGNAL Vector_Interpolation_validOut    : std_logic;
  SIGNAL To_DAC_Interface_dacDataI        : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]
  SIGNAL To_DAC_Interface_dacDataQ        : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]
  SIGNAL To_DAC_Interface_dacValid        : std_logic;

BEGIN
  u_From_Data_Bus : QPSK_src_From_Data_Bus
    PORT MAP( bus_data_re => TxBus_data_re,  -- sfix16_En14
              bus_data_im => TxBus_data_im,  -- sfix16_En14
              bus_valid => TxBus_valid,
              data_re => From_Data_Bus_data_re,  -- sfix16_En14
              data_im => From_Data_Bus_data_im,  -- sfix16_En14
              valid => From_Data_Bus_valid
              );

  u_Apply_Gain : QPSK_src_Apply_Gain_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => From_Data_Bus_data_re,  -- sfix16_En14
              dataIn_im => From_Data_Bus_data_im,  -- sfix16_En14
              validIn => From_Data_Bus_valid,
              tx_output_gain => tx_output_gain,  -- sfix18_En15
              dataOut_re => Apply_Gain_dataOut_re,  -- sfix16_En14
              dataOut_im => Apply_Gain_dataOut_im,  -- sfix16_En14
              validOut => Apply_Gain_validOut
              );

  u_Vector_Interpolation : QPSK_src_Vector_Interpolation
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => Apply_Gain_dataOut_re,  -- sfix16_En14
              dataIn_im => Apply_Gain_dataOut_im,  -- sfix16_En14
              validIn => Apply_Gain_validOut,
              dataOut_re => Vector_Interpolation_dataOut_re,  -- sfix16_En14 [4]
              dataOut_im => Vector_Interpolation_dataOut_im,  -- sfix16_En14 [4]
              validOut => Vector_Interpolation_validOut
              );

  u_To_DAC_Interface : QPSK_src_To_DAC_Interface
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => Vector_Interpolation_dataOut_re,  -- sfix16_En14 [4]
              dataIn_im => Vector_Interpolation_dataOut_im,  -- sfix16_En14 [4]
              validIn => Vector_Interpolation_validOut,
              tx_enable => tx_enable,
              dacDataI => To_DAC_Interface_dacDataI,  -- int16 [4]
              dacDataQ => To_DAC_Interface_dacDataQ,  -- int16 [4]
              dacValid => To_DAC_Interface_dacValid
              );

  dacDataI <= To_DAC_Interface_dacDataI;

  dacDataQ <= To_DAC_Interface_dacDataQ;

  dacValid <= To_DAC_Interface_dacValid;

END rtl;

