-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_axi4_stream_dma_master.vhd
-- Created: 2025-09-17 13:28:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_axi4_stream_dma_master
-- Source Path: QPSK/QPSK_axi4_stream_dma_master
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_axi4_stream_dma_master IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_DMA_Master_TREADY     :   IN    std_logic;  -- ufix1
        user_data                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        user_valid                        :   IN    std_logic;  -- ufix1
        user_TLAST                        :   IN    std_logic;  -- ufix1
        AXI4_Stream_DMA_Master_TDATA      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Stream_DMA_Master_TVALID     :   OUT   std_logic;  -- ufix1
        AXI4_Stream_DMA_Master_TLAST      :   OUT   std_logic;  -- ufix1
        user_ready                        :   OUT   std_logic  -- ufix1
        );
END QPSK_axi4_stream_dma_master;


ARCHITECTURE rtl OF QPSK_axi4_stream_dma_master IS

  -- Component Declarations
  COMPONENT QPSK_fifo_data_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          Empty                           :   OUT   std_logic;  -- ufix1
          AFull                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT QPSK_fifo_TLAST_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic;  -- ufix1
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_fifo_data_OUT
    USE ENTITY work.QPSK_fifo_data_OUT(rtl);

  FOR ALL : QPSK_fifo_TLAST_OUT
    USE ENTITY work.QPSK_fifo_TLAST_OUT(rtl);

  -- Signals
  SIGNAL AXI4_Stream_DMA_Master_TDATA_tmp : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL fifo_empty_data                  : std_logic;  -- ufix1
  SIGNAL fifo_afull_data                  : std_logic;  -- ufix1
  SIGNAL internal_ready                   : std_logic;  -- ufix1

BEGIN
  u_QPSK_fifo_data_OUT_inst : QPSK_fifo_data_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_data,  -- ufix32
              Push => user_valid,  -- ufix1
              Pop => AXI4_Stream_DMA_Master_TREADY,  -- ufix1
              Out_rsvd => AXI4_Stream_DMA_Master_TDATA_tmp,  -- ufix32
              Empty => fifo_empty_data,  -- ufix1
              AFull => fifo_afull_data  -- ufix1
              );

  u_QPSK_fifo_TLAST_OUT_inst : QPSK_fifo_TLAST_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_TLAST,  -- ufix1
              Push => user_valid,  -- ufix1
              Pop => AXI4_Stream_DMA_Master_TREADY,  -- ufix1
              Out_rsvd => AXI4_Stream_DMA_Master_TLAST  -- ufix1
              );

  AXI4_Stream_DMA_Master_TVALID <=  NOT fifo_empty_data;

  internal_ready <=  NOT fifo_afull_data;

  AXI4_Stream_DMA_Master_TDATA <= AXI4_Stream_DMA_Master_TDATA_tmp;

  user_ready <= internal_ready;

END rtl;

