-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_Zeros_Like.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_Zeros_Like
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Tx/Output Switch/Zero On Invalid/Zeros Like
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_Zeros_Like IS
  PORT( u_re                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        u_im                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        y_re                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        y_im                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END QPSK_src_Zeros_Like;


ARCHITECTURE rtl OF QPSK_src_Zeros_Like IS

  -- Signals
  SIGNAL u_re_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL u_im_signed                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL y_re_tmp                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL y_im_tmp                         : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_re_signed <= signed(u_re);

  u_im_signed <= signed(u_im);

  --MATLAB Function 'QPSK/QPSK Tx/Output Switch/Zero On Invalid/Zeros Like'
  y_re_tmp <= to_signed(16#0000#, 16);
  y_im_tmp <= to_signed(16#0000#, 16);

  y_re <= std_logic_vector(y_re_tmp);

  y_im <= std_logic_vector(y_im_tmp);

END rtl;

