-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_FilterTapSystolicWvldInC0.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_FilterTapSystolicWvldInC0
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/From ADC/Vector Decimation/FIR Decimator/FilterBank/subFilter/FilterTapSystolicWvldInC0
-- Hierarchy Level: 6
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_FilterTapSystolicWvldInC0 IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_3_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        addin                             :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En30
        dinRegVld                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tapout                            :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En30
        );
END QPSK_src_FilterTapSystolicWvldInC0;


ARCHITECTURE rtl OF QPSK_src_FilterTapSystolicWvldInC0 IS

  -- Signals
  SIGNAL dinReg2_3_re_signed              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL addin_signed                     : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL fTap_din1_reg1                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_din1_reg2                   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16
  SIGNAL fTap_addout_reg                  : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_din1_reg1_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_din1_reg2_next              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL fTap_addout_reg_next             : signed(47 DOWNTO 0);  -- sfix48_En30
  SIGNAL dinDly2_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tapout_tmp                       : signed(47 DOWNTO 0);  -- sfix48_En30

BEGIN
  dinReg2_3_re_signed <= signed(dinReg2_3_re);

  addin_signed <= signed(addin);

  -- FilterTapSystolicWvldInC0
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fTap_din1_reg1 <= fTap_din1_reg1_next;
        fTap_din1_reg2 <= fTap_din1_reg2_next;
        fTap_addout_reg <= fTap_addout_reg_next;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, dinReg2_3_re_signed, dinRegVld, fTap_addout_reg, fTap_din1_reg1,
       fTap_din1_reg2)
  BEGIN
    fTap_din1_reg1_next <= fTap_din1_reg1;
    fTap_din1_reg2_next <= fTap_din1_reg2;
    fTap_addout_reg_next <= fTap_addout_reg;
    IF dinRegVld = '1' THEN 
      fTap_addout_reg_next <= addin_signed;
    END IF;
    IF dinRegVld = '1' THEN 
      fTap_din1_reg2_next <= fTap_din1_reg1;
      fTap_din1_reg1_next <= dinReg2_3_re_signed;
    END IF;
    dinDly2_tmp <= fTap_din1_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

