-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_From_Data_Bus_block.vhd
-- Created: 2025-09-17 13:27:53
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_From_Data_Bus_block
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/To DMA/Capture Source Mux/Data to uint32/From Data Bus
-- Hierarchy Level: 4
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_From_Data_Bus_block IS
  PORT( bus_data_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bus_data_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bus_valid                         :   IN    std_logic;
        data_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        data_im                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        valid                             :   OUT   std_logic
        );
END QPSK_src_From_Data_Bus_block;


ARCHITECTURE rtl OF QPSK_src_From_Data_Bus_block IS

  -- Signals
  SIGNAL data_re_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL data_im_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  data_re_tmp <= signed(bus_data_re);

  data_re <= std_logic_vector(data_re_tmp);

  data_im_tmp <= signed(bus_data_im);

  data_im <= std_logic_vector(data_im_tmp);

  valid <= bus_valid;

END rtl;

