-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_FIR_Decimator.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_FIR_Decimator
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/From ADC/Vector Decimation/FIR Decimator
-- Hierarchy Level: 3
-- Model version: 9.4
-- 
-- HDL FIR Decimation
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_src_QPSK_pkg.ALL;

ENTITY QPSK_src_FIR_Decimator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
        dataIn_im                         :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En30
        dataOut_im                        :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En30
        validOut                          :   OUT   std_logic
        );
END QPSK_src_FIR_Decimator;


ARCHITECTURE rtl OF QPSK_src_FIR_Decimator IS

  -- Component Declarations
  COMPONENT QPSK_src_FilterBank
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterIn_re                     :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          filterIn_im                     :   IN    vector_of_std_logic_vector16(0 TO 3);  -- sfix16_En14 [4]
          validIn                         :   IN    std_logic;
          filterOut_re                    :   OUT   vector_of_std_logic_vector33(0 TO 3);  -- sfix33_En30 [4]
          filterOut_im                    :   OUT   vector_of_std_logic_vector33(0 TO 3);  -- sfix33_En30 [4]
          filterOut_vld                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT QPSK_src_sumTree
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterOut_re                    :   IN    vector_of_std_logic_vector33(0 TO 3);  -- sfix33_En30 [4]
          filterOut_im                    :   IN    vector_of_std_logic_vector33(0 TO 3);  -- sfix33_En30 [4]
          filterOut_vld                   :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En30
          dataOut_im                      :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En30
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_FilterBank
    USE ENTITY work.QPSK_src_FilterBank(rtl);

  FOR ALL : QPSK_src_sumTree
    USE ENTITY work.QPSK_src_sumTree(rtl);

  -- Signals
  SIGNAL filterOut_re                     : vector_of_std_logic_vector33(0 TO 3);  -- ufix33 [4]
  SIGNAL filterOut_im                     : vector_of_std_logic_vector33(0 TO 3);  -- ufix33 [4]
  SIGNAL filterOut_vld                    : std_logic;
  SIGNAL dataOut_re_tmp                   : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL dataOut_im_tmp                   : std_logic_vector(32 DOWNTO 0);  -- ufix33

BEGIN
  u_FilterBank : QPSK_src_FilterBank
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterIn_re => dataIn_re,  -- sfix16_En14 [4]
              filterIn_im => dataIn_im,  -- sfix16_En14 [4]
              validIn => validIn,
              filterOut_re => filterOut_re,  -- sfix33_En30 [4]
              filterOut_im => filterOut_im,  -- sfix33_En30 [4]
              filterOut_vld => filterOut_vld
              );

  u_FirDecimAcc : QPSK_src_sumTree
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterOut_re => filterOut_re,  -- sfix33_En30 [4]
              filterOut_im => filterOut_im,  -- sfix33_En30 [4]
              filterOut_vld => filterOut_vld,
              dataOut_re => dataOut_re_tmp,  -- sfix33_En30
              dataOut_im => dataOut_im_tmp,  -- sfix33_En30
              validOut => validOut
              );

  dataOut_re <= dataOut_re_tmp;

  dataOut_im <= dataOut_im_tmp;

END rtl;

