-- -------------------------------------------------------------
-- 
-- File Name: C:\QPSK\hdl_prj_zcu111\hdlsrc\hdlcoder_QPSKTxRx_RFSoC\QPSK_src_QPSK_Modulator.vhd
-- Created: 2025-09-17 13:27:52
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: QPSK_src_QPSK_Modulator
-- Source Path: hdlcoder_QPSKTxRx_RFSoC/QPSK/QPSK Tx/QPSK Modulator
-- Hierarchy Level: 2
-- Model version: 9.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY QPSK_src_QPSK_Modulator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic;
        validIn                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validOut                          :   OUT   std_logic
        );
END QPSK_src_QPSK_Modulator;


ARCHITECTURE rtl OF QPSK_src_QPSK_Modulator IS

  -- Component Declarations
  COMPONENT QPSK_src_QPSK_Modulator_Baseband
    PORT( in0                             :   IN    std_logic_vector(1 DOWNTO 0);  -- boolean [2]
          out0_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          out0_im                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : QPSK_src_QPSK_Modulator_Baseband
    USE ENTITY work.QPSK_src_QPSK_Modulator_Baseband(rtl);

  -- Signals
  SIGNAL modBitIn                         : std_logic;
  SIGNAL modBitValidIn                    : std_logic;
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL count_step                       : std_logic;  -- ufix1
  SIGNAL count_from                       : std_logic;  -- ufix1
  SIGNAL count                            : std_logic;  -- ufix1
  SIGNAL count_1                          : std_logic;  -- ufix1
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : std_logic;  -- ufix1
  SIGNAL count_2                          : std_logic;  -- ufix1
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL modInValid                       : std_logic;
  SIGNAL Delay12_out1                     : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Null_out1_re                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Null_out1_im                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Unit_Delay_Enabled_Synchronous_out1 : std_logic;
  SIGNAL Mux_out1                         : std_logic_vector(1 DOWNTO 0);  -- boolean [2]
  SIGNAL modIn                            : std_logic_vector(1 DOWNTO 0);  -- boolean [2]
  SIGNAL QPSK_Modulator_Baseband_out1_re  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL QPSK_Modulator_Baseband_out1_im  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL QPSK_Modulator_Baseband_out1_re_signed : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL QPSK_Modulator_Baseband_out1_im_signed : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay11_out1_re                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay11_out1_im                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Switch3_out1_re                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Switch3_out1_im                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL QPSKConstellationPoints_re       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL QPSKConstellationPoints_im       : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay3_out1                      : std_logic;

BEGIN
  u_QPSK_Modulator_Baseband : QPSK_src_QPSK_Modulator_Baseband
    PORT MAP( in0 => modIn,  -- boolean [2]
              out0_re => QPSK_Modulator_Baseband_out1_re,  -- sfix16_En15
              out0_im => QPSK_Modulator_Baseband_out1_im  -- sfix16_En15
              );

  modBitIn <= dataIn;

  modBitValidIn <= validIn;

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1 <= modBitValidIn;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1
  count_step <= '1';

  count_from <= '0';

  count_1 <= count XOR count_step;

  
  need_to_wrap <= '1' WHEN count = '1' ELSE
      '0';

  
  count_value <= count_1 WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_2 <= count WHEN Delay1_out1 = '0' ELSE
      count_value;

  HDL_Counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count <= '0';
      ELSIF enb = '1' THEN
        count <= count_2;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN count = '1' ELSE
      '0';

  Logical_Operator1_out1 <= Compare_To_Constant1_out1 AND Delay1_out1;

  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        modInValid <= '0';
      ELSIF enb = '1' THEN
        modInValid <= Logical_Operator1_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Delay12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay12_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay12_out1 <= modInValid;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  
  switch_compare_1 <= '1' WHEN Delay12_out1 = '1' ELSE
      '0';

  Null_out1_re <= to_signed(16#0000#, 16);
  Null_out1_im <= to_signed(16#0000#, 16);

  
  Compare_To_Constant_out1 <= '1' WHEN count = '0' ELSE
      '0';

  Logical_Operator_out1 <= Delay1_out1 AND Compare_To_Constant_out1;

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay_out1 <= modBitIn;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= '0';
      ELSIF enb = '1' AND Logical_Operator_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  Mux_out1(0) <= Unit_Delay_Enabled_Synchronous_out1;
  Mux_out1(1) <= Delay_out1;

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        modIn <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        modIn <= Mux_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  QPSK_Modulator_Baseband_out1_re_signed <= signed(QPSK_Modulator_Baseband_out1_re);

  QPSK_Modulator_Baseband_out1_im_signed <= signed(QPSK_Modulator_Baseband_out1_im);

  Delay11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay11_out1_re <= to_signed(16#0000#, 16);
        Delay11_out1_im <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay11_out1_re <= QPSK_Modulator_Baseband_out1_re_signed;
        Delay11_out1_im <= QPSK_Modulator_Baseband_out1_im_signed;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  
  Switch3_out1_re <= Null_out1_re WHEN switch_compare_1 = '0' ELSE
      Delay11_out1_re;
  
  Switch3_out1_im <= Null_out1_im WHEN switch_compare_1 = '0' ELSE
      Delay11_out1_im;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        QPSKConstellationPoints_re <= to_signed(16#0000#, 16);
        QPSKConstellationPoints_im <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        QPSKConstellationPoints_re <= Switch3_out1_re;
        QPSKConstellationPoints_im <= Switch3_out1_im;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  dataOut_re <= std_logic_vector(QPSKConstellationPoints_re);

  dataOut_im <= std_logic_vector(QPSKConstellationPoints_im);

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1 <= Delay12_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  validOut <= Delay3_out1;

END rtl;

