set_property SRC_FILE_INFO {cfile:C:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.srcs/constrs_1/imports/fpga/fpga_r2.xdc rfile:../../../Taxi_QPSK_v3.srcs/constrs_1/imports/fpga/fpga_r2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C8 IOSTANDARD LVDS_25} [get_ports clk_pl_user1_p]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C7 IOSTANDARD LVDS_25} [get_ports clk_pl_user1_n]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV6 IOSTANDARD LVDS_25} [get_ports fpga_refclk_p]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV5 IOSTANDARD LVDS_25} [get_ports fpga_refclk_n]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets fpga_refclk_int fpga_refclk_bufg_inst_n_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AP20 IOSTANDARD LVDS} [get_ports fpga_sysref_p]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AP19 IOSTANDARD LVDS} [get_ports fpga_sysref_n]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU4 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports clk_fdec]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV2 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports clk_finc]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU1 IOSTANDARD LVCMOS33} [get_ports clk_intr_n]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV3 IOSTANDARD LVCMOS33} [get_ports clk_lol_n]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU3 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports clk_sync_n]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU2 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports clk_rst_n]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW6 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports lmk_rst]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW4 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {lmk_clkin_s[0]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW3 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {lmk_clkin_s[1]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A6 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C6 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D6 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E6 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AT5 IOSTANDARD LVCMOS33} [get_ports btn]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D20 IOSTANDARD LVCMOS12} [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A25 IOSTANDARD LVCMOS12} [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B23 IOSTANDARD LVCMOS12} [get_ports {sw[2]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D19 IOSTANDARD LVCMOS12} [get_ports {sw[3]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU8 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV8 IOSTANDARD LVCMOS33} [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV7 IOSTANDARD LVCMOS33} [get_ports uart_rts]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU7 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports uart_cts]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AT7 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports uart_rst_n]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AR7 IOSTANDARD LVCMOS33} [get_ports uart_suspend_n]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E9 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports i2c_scl]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E8 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports i2c_sda]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D10 IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 8} [get_ports i2c_rst_n]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AJ12 IOSTANDARD LVCMOS18} [get_ports fmc_qsfp_resetl]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AK12 IOSTANDARD LVCMOS18} [get_ports fmc_qsfp_modsell]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AL7 IOSTANDARD LVCMOS18} [get_ports fmc_qsfp_lpmode]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E33} [get_ports {fmc_dp_c2m_p[0]}]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E34} [get_ports {fmc_dp_c2m_n[0]}]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F36} [get_ports {fmc_dp_m2c_p[0]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F37} [get_ports {fmc_dp_m2c_n[0]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC H31} [get_ports {fmc_dp_c2m_p[1]}]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC H32} [get_ports {fmc_dp_c2m_n[1]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J38} [get_ports {fmc_dp_m2c_p[1]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J39} [get_ports {fmc_dp_m2c_n[1]}]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G33} [get_ports {fmc_dp_c2m_p[2]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G34} [get_ports {fmc_dp_c2m_n[2]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC H36} [get_ports {fmc_dp_m2c_p[2]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC H37} [get_ports {fmc_dp_m2c_n[2]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F31} [get_ports {fmc_dp_c2m_p[3]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC F32} [get_ports {fmc_dp_c2m_n[3]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G38} [get_ports {fmc_dp_m2c_p[3]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G39} [get_ports {fmc_dp_m2c_n[3]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U33} [get_ports fmc_mgt_refclk_0_0_p]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U34} [get_ports fmc_mgt_refclk_0_0_n]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C33} [get_ports {fmc_dp_c2m_p[4]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C34} [get_ports {fmc_dp_c2m_n[4]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D36} [get_ports {fmc_dp_m2c_p[4]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D37} [get_ports {fmc_dp_m2c_n[4]}]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A33} [get_ports {fmc_dp_c2m_p[5]}]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC A34} [get_ports {fmc_dp_c2m_n[5]}]
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B36} [get_ports {fmc_dp_m2c_p[5]}]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B37} [get_ports {fmc_dp_m2c_n[5]}]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B31} [get_ports {fmc_dp_c2m_p[6]}]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC B32} [get_ports {fmc_dp_c2m_n[6]}]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C38} [get_ports {fmc_dp_m2c_p[6]}]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C39} [get_ports {fmc_dp_m2c_n[6]}]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D31} [get_ports {fmc_dp_c2m_p[7]}]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC D32} [get_ports {fmc_dp_c2m_n[7]}]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E38} [get_ports {fmc_dp_m2c_p[7]}]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E39} [get_ports {fmc_dp_m2c_n[7]}]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC P31} [get_ports fmc_mgt_refclk_1_0_p]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC P32} [get_ports fmc_mgt_refclk_1_0_n]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y2} [get_ports {adc_vin_p[0]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y1} [get_ports {adc_vin_n[0]}]
set_property src_info {type:XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB2} [get_ports {adc_vin_p[1]}]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB1} [get_ports {adc_vin_n[1]}]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD2} [get_ports {adc_vin_p[2]}]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD1} [get_ports {adc_vin_n[2]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF2} [get_ports {adc_vin_p[3]}]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF1} [get_ports {adc_vin_n[3]}]
set_property src_info {type:XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AH2} [get_ports {adc_vin_p[4]}]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AH1} [get_ports {adc_vin_n[4]}]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AK2} [get_ports {adc_vin_p[5]}]
set_property src_info {type:XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AK1} [get_ports {adc_vin_n[5]}]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AM2} [get_ports {adc_vin_p[6]}]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AM1} [get_ports {adc_vin_n[6]}]
set_property src_info {type:XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AP2} [get_ports {adc_vin_p[7]}]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AP1} [get_ports {adc_vin_n[7]}]
set_property src_info {type:XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF5} [get_ports adc_refclk_0_p]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AF4} [get_ports adc_refclk_0_n]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD5} [get_ports adc_refclk_1_p]
set_property src_info {type:XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD4} [get_ports adc_refclk_1_n]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB5} [get_ports adc_refclk_2_p]
set_property src_info {type:XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB4} [get_ports adc_refclk_2_n]
set_property src_info {type:XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y5} [get_ports adc_refclk_3_p]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y4} [get_ports adc_refclk_3_n]
set_property src_info {type:XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C2} [get_ports {dac_vout_p[0]}]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C1} [get_ports {dac_vout_n[0]}]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E2} [get_ports {dac_vout_p[1]}]
set_property src_info {type:XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC E1} [get_ports {dac_vout_n[1]}]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G2} [get_ports {dac_vout_p[2]}]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC G1} [get_ports {dac_vout_n[2]}]
set_property src_info {type:XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J2} [get_ports {dac_vout_p[3]}]
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC J1} [get_ports {dac_vout_n[3]}]
set_property src_info {type:XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC L2} [get_ports {dac_vout_p[4]}]
set_property src_info {type:XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC L1} [get_ports {dac_vout_n[4]}]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N2} [get_ports {dac_vout_p[5]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N1} [get_ports {dac_vout_n[5]}]
set_property src_info {type:XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC R2} [get_ports {dac_vout_p[6]}]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC R1} [get_ports {dac_vout_n[6]}]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U2} [get_ports {dac_vout_p[7]}]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U1} [get_ports {dac_vout_n[7]}]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N5} [get_ports dac_refclk_1_p]
set_property src_info {type:XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N4} [get_ports dac_refclk_1_n]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U5} [get_ports rfdc_sysref_p]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC U4} [get_ports rfdc_sysref_n]
