# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.srcs/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/qpsk_for_htg_system_ila_0_0.xci
# IP: The module: 'qpsk_for_htg_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/bd_302b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b || ORIG_REF_NAME==bd_302b} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/bd_302b_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_1/bd_302b_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_g_inst_0 || ORIG_REF_NAME==bd_302b_g_inst_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_2/bd_302b_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_aw_0 || ORIG_REF_NAME==bd_302b_slot_0_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_3/bd_302b_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_w_0 || ORIG_REF_NAME==bd_302b_slot_0_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_4/bd_302b_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_b_0 || ORIG_REF_NAME==bd_302b_slot_0_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_5/bd_302b_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_ar_0 || ORIG_REF_NAME==bd_302b_slot_0_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_6/bd_302b_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_r_0 || ORIG_REF_NAME==bd_302b_slot_0_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_7/bd_302b_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_aw_0 || ORIG_REF_NAME==bd_302b_slot_1_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_8/bd_302b_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_w_0 || ORIG_REF_NAME==bd_302b_slot_1_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_9/bd_302b_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_b_0 || ORIG_REF_NAME==bd_302b_slot_1_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_10/bd_302b_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_ar_0 || ORIG_REF_NAME==bd_302b_slot_1_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_11/bd_302b_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_r_0 || ORIG_REF_NAME==bd_302b_slot_1_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_12/bd_302b_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_aw_0 || ORIG_REF_NAME==bd_302b_slot_2_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_13/bd_302b_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_w_0 || ORIG_REF_NAME==bd_302b_slot_2_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_14/bd_302b_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_b_0 || ORIG_REF_NAME==bd_302b_slot_2_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_15/bd_302b_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_ar_0 || ORIG_REF_NAME==bd_302b_slot_2_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_16/bd_302b_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_r_0 || ORIG_REF_NAME==bd_302b_slot_2_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_17/bd_302b_slot_3_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_aw_0 || ORIG_REF_NAME==bd_302b_slot_3_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_18/bd_302b_slot_3_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_w_0 || ORIG_REF_NAME==bd_302b_slot_3_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_19/bd_302b_slot_3_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_b_0 || ORIG_REF_NAME==bd_302b_slot_3_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_20/bd_302b_slot_3_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_ar_0 || ORIG_REF_NAME==bd_302b_slot_3_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_21/bd_302b_slot_3_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_r_0 || ORIG_REF_NAME==bd_302b_slot_3_r_0} -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/bd_302b_ila_lib_0_ooc.xdc

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/bd_302b_ooc.xdc

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/qpsk_for_htg_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qpsk_for_htg_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.srcs/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/qpsk_for_htg_system_ila_0_0.xci
# IP: The module: 'qpsk_for_htg_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/bd_302b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b || ORIG_REF_NAME==bd_302b} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/bd_302b_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_1/bd_302b_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_g_inst_0 || ORIG_REF_NAME==bd_302b_g_inst_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_2/bd_302b_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_aw_0 || ORIG_REF_NAME==bd_302b_slot_0_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_3/bd_302b_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_w_0 || ORIG_REF_NAME==bd_302b_slot_0_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_4/bd_302b_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_b_0 || ORIG_REF_NAME==bd_302b_slot_0_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_5/bd_302b_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_ar_0 || ORIG_REF_NAME==bd_302b_slot_0_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_6/bd_302b_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_0_r_0 || ORIG_REF_NAME==bd_302b_slot_0_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_7/bd_302b_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_aw_0 || ORIG_REF_NAME==bd_302b_slot_1_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_8/bd_302b_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_w_0 || ORIG_REF_NAME==bd_302b_slot_1_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_9/bd_302b_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_b_0 || ORIG_REF_NAME==bd_302b_slot_1_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_10/bd_302b_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_ar_0 || ORIG_REF_NAME==bd_302b_slot_1_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_11/bd_302b_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_1_r_0 || ORIG_REF_NAME==bd_302b_slot_1_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_12/bd_302b_slot_2_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_aw_0 || ORIG_REF_NAME==bd_302b_slot_2_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_13/bd_302b_slot_2_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_w_0 || ORIG_REF_NAME==bd_302b_slot_2_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_14/bd_302b_slot_2_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_b_0 || ORIG_REF_NAME==bd_302b_slot_2_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_15/bd_302b_slot_2_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_ar_0 || ORIG_REF_NAME==bd_302b_slot_2_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_16/bd_302b_slot_2_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_2_r_0 || ORIG_REF_NAME==bd_302b_slot_2_r_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_17/bd_302b_slot_3_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_aw_0 || ORIG_REF_NAME==bd_302b_slot_3_aw_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_18/bd_302b_slot_3_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_w_0 || ORIG_REF_NAME==bd_302b_slot_3_w_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_19/bd_302b_slot_3_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_b_0 || ORIG_REF_NAME==bd_302b_slot_3_b_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_20/bd_302b_slot_3_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_ar_0 || ORIG_REF_NAME==bd_302b_slot_3_ar_0} -quiet] -quiet

# IP: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_21/bd_302b_slot_3_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_302b_slot_3_r_0 || ORIG_REF_NAME==bd_302b_slot_3_r_0} -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_302b_ila_lib_0 || ORIG_REF_NAME==bd_302b_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/ip/ip_0/bd_302b_ila_lib_0_ooc.xdc

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/bd_0/bd_302b_ooc.xdc

# XDC: c:/Taxi/temp_back_of_v3/Taxi_QPSK_v3/Taxi_QPSK_v3/Taxi_QPSK_v3.gen/sources_1/bd/qpsk_for_htg/ip/qpsk_for_htg_system_ila_0_0/qpsk_for_htg_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qpsk_for_htg_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
