function gs_hdlcoder_QPSKTxRx_RFSoC_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 25.1 (R2025a) at 12:20:20 on 01/09/2025.
% This function was created for the IP Core generated from design 'hdlcoder_QPSKTxRx_RFSoC'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0xA0000000, ...
	"AddressRange", 0x10000);

DUTPort_regIn_tx_enable = hdlcoder.DUTPort("tx_enable", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_regIn_rx_reset_cs = hdlcoder.DUTPort("rx_reset_cs", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

DUTPort_regIn_rx_src_sel = hdlcoder.DUTPort("rx_src_sel", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,1,0), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x108");

DUTPort_regIn_capture_start = hdlcoder.DUTPort("capture_start", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x10C");

DUTPort_regIn_capture_length = hdlcoder.DUTPort("capture_length", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x110");

DUTPort_regIn_capture_src_sel = hdlcoder.DUTPort("capture_src_sel", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,1,0), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x114");

DUTPort_regIn_tx_output_gain = hdlcoder.DUTPort("tx_output_gain", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,15), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x118");

DUTPort_regIn_rx_input_gain = hdlcoder.DUTPort("rx_input_gain", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,18,15), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x11C");

DUTPort_regIn_capture_mode = hdlcoder.DUTPort("capture_mode", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,2,0), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x120");

DUTPort_regIn = hdlcoder.DUTPort("regIn", ...
	"Direction", "IN", ...
	"DataType", "Bus", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"SubPorts", [DUTPort_regIn_tx_enable, DUTPort_regIn_rx_reset_cs, DUTPort_regIn_rx_src_sel, DUTPort_regIn_capture_start, DUTPort_regIn_capture_length, DUTPort_regIn_capture_src_sel, DUTPort_regIn_tx_output_gain, DUTPort_regIn_rx_input_gain, DUTPort_regIn_capture_mode]);

DUTPort_regOut_rx_nSynced = hdlcoder.DUTPort("rx_nSynced", ...
	"Direction", "OUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x124");

DUTPort_regOut_rx_normCoarseFreqEst = hdlcoder.DUTPort("rx_normCoarseFreqEst", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,21,21), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x128");

DUTPort_regOut = hdlcoder.DUTPort("regOut", ...
	"Direction", "OUT", ...
	"DataType", "Bus", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"SubPorts", [DUTPort_regOut_rx_nSynced, DUTPort_regOut_rx_normCoarseFreqEst]);

mapPort(hFPGA, [DUTPort_regIn, DUTPort_regOut]);

%% AXI4-Stream DMA
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream DMA", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 32, ...
	"WriteFrameLength", 1024, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 32, ...
	"ReadFrameLength", 1024);

DUTPort_mm2sData = hdlcoder.DUTPort("mm2sData", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream DMA");

DUTPort_s2mmData = hdlcoder.DUTPort("s2mmData", ...
	"Direction", "OUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream DMA");

mapPort(hFPGA, [DUTPort_mm2sData, DUTPort_s2mmData]);

end
