# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.srcs/sources_1/ip/taxi_eth_phy_25g_us_gty_full/taxi_eth_phy_25g_us_gty_full.xci
# IP: The module: 'taxi_eth_phy_25g_us_gty_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.gen/sources_1/ip/taxi_eth_phy_25g_us_gty_full/synth/taxi_eth_phy_25g_us_gty_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'taxi_eth_phy_25g_us_gty_full'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.gen/sources_1/ip/taxi_eth_phy_25g_us_gty_full/synth/taxi_eth_phy_25g_us_gty_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'taxi_eth_phy_25g_us_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.srcs/sources_1/ip/taxi_eth_phy_25g_us_gty_full/taxi_eth_phy_25g_us_gty_full.xci
# IP: The module: 'taxi_eth_phy_25g_us_gty_full' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.gen/sources_1/ip/taxi_eth_phy_25g_us_gty_full/synth/taxi_eth_phy_25g_us_gty_full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'taxi_eth_phy_25g_us_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/sarial/intellifpga/taxi/src/eth/example/HTG_ZRF8/fpga/fpga_R2_ZU48DR/fpga.gen/sources_1/ip/taxi_eth_phy_25g_us_gty_full/synth/taxi_eth_phy_25g_us_gty_full.xdc
# XDC: The top module name and the constraint reference have the same name: 'taxi_eth_phy_25g_us_gty_full'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
